In [7]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime

In [1]:
from scripts import project_functions # This is called a relative import
data = project_functions.load_and_process('/Users/takumi/Documents/DATA301_1023/course-project-group_1023/data/raw/weatherAUS.csv')
data

,Date,Location,MinTemp,MaxTemp,Percipitation,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
0,2008-12-01,Albury,13.4,22.9,0.6,W,44.0,W,WNW,20.0,24.0,71.0,22.0,1007.7,1007.1,16.9,21.8
1,2008-12-02,Albury,7.4,25.1,0.0,WNW,44.0,NNW,WSW,4.0,22.0,44.0,25.0,1010.6,1007.8,17.2,24.3
2,2008-12-03,Albury,12.9,25.7,0.0,WSW,46.0,W,WSW,19.0,26.0,38.0,30.0,1007.6,1008.7,21.0,23.2
3,2008-12-04,Albury,9.2,28.0,0.0,NE,24.0,SE,E,11.0,9.0,45.0,16.0,1017.6,1012.8,18.1,26.5
4,2008-12-05,Albury,17.5,32.3,1.0,W,41.0,ENE,NW,7.0,20.0,82.0,33.0,1010.8,1006.0,17.8,29.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113674,2017-06-20,Uluru,3.5,21.8,0.0,E,31.0,ESE,E,15.0,13.0,59.0,27.0,1024.7,1021.2,9.4,20.9
113675,2017-06-21,Uluru,2.8,23.4,0.0,E,31.0,SE,ENE,13.0,11.0,51.0,24.0,1024.6,1020.3,10.1,22.4
113676,2017-06-22,Uluru,3.6,25.3,0.0,NNW,22.0,SE,N,13.0,9.0,56.0,21.0,1023.5,1019.1,10.9,24.5
113677,2017-06-23,Uluru,5.4,26.9,0.0,N,37.0,SE,WNW,9.0,9.0,53.0,24.0,1021.0,1016.8,12.5,26.1
113678,2017-06-24,Uluru,7.8,27.0,0.0,SE,28.0,SSE,N,13.0,7.0,51.0,24.0,1019.4,1016.5,15.1,26.0

In [11]:
### getting data only in sydney 
data_in_sydney=  data[data["Location"]=='Sydney']
data_in_sydney

,Date,Location,MinTemp,MaxTemp,Percipitation,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm
20558,2010-10-09,Sydney,15.8,18.9,0.0,ESE,31.0,ESE,ENE,20.0,11.0,59.0,55.0,1026.4,1025.3,17.0,18.3
20559,2010-10-14,Sydney,17.8,28.9,2.0,NNW,41.0,NNW,E,22.0,17.0,63.0,48.0,1011.2,1008.1,22.3,26.6
20560,2010-10-15,Sydney,19.5,24.7,0.0,NNW,76.0,NE,NE,13.0,31.0,66.0,73.0,999.6,989.8,21.5,21.8
20561,2010-10-16,Sydney,11.7,16.1,0.8,WNW,85.0,W,W,46.0,48.0,34.0,28.0,999.3,1003.6,12.9,15.2
20562,2010-10-17,Sydney,9.9,24.0,0.0,W,41.0,W,SSE,24.0,4.0,44.0,30.0,1012.9,1011.3,14.7,23.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22816,2017-06-21,Sydney,8.6,19.6,0.0,SSE,37.0,W,SSE,22.0,20.0,73.0,52.0,1025.9,1025.3,10.5,17.9
22817,2017-06-22,Sydney,9.3,19.2,0.0,W,30.0,W,ESE,20.0,7.0,78.0,53.0,1028.5,1024.6,11.0,18.7
22818,2017-06-23,Sydney,9.4,17.7,0.0,W,24.0,WNW,N,15.0,13.0,85.0,56.0,1020.8,1015.0,10.2,17.3
22819,2017-06-24,Sydney,10.1,19.3,0.0,W,43.0,W,W,17.0,19.0,56.0,35.0,1017.3,1015.1,12.4,19.0
22820,2017-06-25,Sydney,7.6,19.3,0.0,W,35.0,W,W,13.0,13.0,73.0,32.0,1018.6,1015.4,9.4,18.8

In [14]:
### adding a new column so that the dataes are in dateime format 
data_in_sydney['Datetime'] = pd.to_datetime(data_in_sydney['Date']).dt.year
data_in_sydney

<ipython-input-14-9922ddcbd648>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_in_sydney['Datetime'] = pd.to_datetime(data_in_sydney['Date']).dt.year

,Date,Location,MinTemp,MaxTemp,Percipitation,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,Datetime
20558,2010-10-09,Sydney,15.8,18.9,0.0,ESE,31.0,ESE,ENE,20.0,11.0,59.0,55.0,1026.4,1025.3,17.0,18.3,2010
20559,2010-10-14,Sydney,17.8,28.9,2.0,NNW,41.0,NNW,E,22.0,17.0,63.0,48.0,1011.2,1008.1,22.3,26.6,2010
20560,2010-10-15,Sydney,19.5,24.7,0.0,NNW,76.0,NE,NE,13.0,31.0,66.0,73.0,999.6,989.8,21.5,21.8,2010
20561,2010-10-16,Sydney,11.7,16.1,0.8,WNW,85.0,W,W,46.0,48.0,34.0,28.0,999.3,1003.6,12.9,15.2,2010
20562,2010-10-17,Sydney,9.9,24.0,0.0,W,41.0,W,SSE,24.0,4.0,44.0,30.0,1012.9,1011.3,14.7,23.3,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22816,2017-06-21,Sydney,8.6,19.6,0.0,SSE,37.0,W,SSE,22.0,20.0,73.0,52.0,1025.9,1025.3,10.5,17.9,2017
22817,2017-06-22,Sydney,9.3,19.2,0.0,W,30.0,W,ESE,20.0,7.0,78.0,53.0,1028.5,1024.6,11.0,18.7,2017
22818,2017-06-23,Sydney,9.4,17.7,0.0,W,24.0,WNW,N,15.0,13.0,85.0,56.0,1020.8,1015.0,10.2,17.3,2017
22819,2017-06-24,Sydney,10.1,19.3,0.0,W,43.0,W,W,17.0,19.0,56.0,35.0,1017.3,1015.1,12.4,19.0,2017
22820,2017-06-25,Sydney,7.6,19.3,0.0,W,35.0,W,W,13.0,13.0,73.0,32.0,1018.6,1015.4,9.4,18.8,2017

In [9]:
### trying to split the dates into year and month-day. 

dates= datetime.datetime.strptime(data_in_sydney['Date'], "%Y")

TypeError: strptime() argument 1 must be str, not Series

In [13]:
data_in_sydney

,Date,Location,MinTemp,MaxTemp,Percipitation,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Temp9am,Temp3pm,Datetime
20558,2010-10-09,Sydney,15.8,18.9,0.0,ESE,31.0,ESE,ENE,20.0,11.0,59.0,55.0,1026.4,1025.3,17.0,18.3,2010
20559,2010-10-14,Sydney,17.8,28.9,2.0,NNW,41.0,NNW,E,22.0,17.0,63.0,48.0,1011.2,1008.1,22.3,26.6,2010
20560,2010-10-15,Sydney,19.5,24.7,0.0,NNW,76.0,NE,NE,13.0,31.0,66.0,73.0,999.6,989.8,21.5,21.8,2010
20561,2010-10-16,Sydney,11.7,16.1,0.8,WNW,85.0,W,W,46.0,48.0,34.0,28.0,999.3,1003.6,12.9,15.2,2010
20562,2010-10-17,Sydney,9.9,24.0,0.0,W,41.0,W,SSE,24.0,4.0,44.0,30.0,1012.9,1011.3,14.7,23.3,2010
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22816,2017-06-21,Sydney,8.6,19.6,0.0,SSE,37.0,W,SSE,22.0,20.0,73.0,52.0,1025.9,1025.3,10.5,17.9,2017
22817,2017-06-22,Sydney,9.3,19.2,0.0,W,30.0,W,ESE,20.0,7.0,78.0,53.0,1028.5,1024.6,11.0,18.7,2017
22818,2017-06-23,Sydney,9.4,17.7,0.0,W,24.0,WNW,N,15.0,13.0,85.0,56.0,1020.8,1015.0,10.2,17.3,2017
22819,2017-06-24,Sydney,10.1,19.3,0.0,W,43.0,W,W,17.0,19.0,56.0,35.0,1017.3,1015.1,12.4,19.0,2017
22820,2017-06-25,Sydney,7.6,19.3,0.0,W,35.0,W,W,13.0,13.0,73.0,32.0,1018.6,1015.4,9.4,18.8,2017